### ISSUE TITLE
Unique numeric IDs for each object

### ISSUE THREAD

**Issue by rochebob** [AnimalHealthInstitute/VFD#2]
As Craig briefly mentioned on our call today, it would be best practice to include unique numeric IDs for each object. My preference would be an externally valid ID (such as license number for vets or NDC code for drugs, etc.)

- Bob

**Comment by odellcraig** [comment]
Craig to create unique ID concept and submit for review

**Comment by odellcraig** [comment]
Ideas:

VFD-20151210112611400

GVL-YEARMMDDHHMMSSMSMS

Purpose: have a unique ID as reference for cross-platform communication that identifies this VFD document.
