### ISSUE TITLE
It doesn't seem like combination drugs are well accounted for.

### ISSUE THREAD

**Issue by aeischeid** [AnimalHealthInstitute/VFD#5]
I see that the drug prop is a list, however, It is my understanding that on a VFD only one VFD regulated drug can be included. Also, drugs approved for use in combination need to be specified along with a combination drug affirmation statement, where the vet specifies one of the following:

* "This VFD ONLY authorizes the use of the VFD drug cited in this order and is NOT intended to authorize the use of such drug in combination with any other animal drugs.",
* "This VFD authorizes the use of the VFD drug cited in this order in ANY FDA-approved, conditionally approved, or indexed combination(s) in medicated feed that contains the VFD drug as a component.",
* "This VFD authorizes the use of the VFD drug cited in this order in THE FOLLOWING FDA-approved, conditionally approved, or indexed combination(s) in medicated feed that contains the VFD drug as a component."

**Comment by aeischeid** [comment]
relates to #1

**Comment by odellcraig** [comment]
@aeischeid to submit PR - thanks!
